# Generated by Django 3.0.5 on 2020-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
    ]
